/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../components/button/index.js';

const components = [
  Button,
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });


  Vue.prototype.$VUPUWP = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

module.exports = {
  version: '0.1.1',
  install,
  Button
};

module.exports.default = module.exports;
